name: Deploy EmployeeApp to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: database-2.cvku0e4qsz38.us-west-2.rds.amazonaws.com
      DB_NAME: employee_db
      DB_USER: admin
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Ensure EC2 deploy folder exists
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/EmployeeApp

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/EmployeeApp-0.0.1-SNAPSHOT.jar"
          target: "~/EmployeeApp/"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f EmployeeApp || true
            nohup java -jar ~/EmployeeApp/EmployeeApp-0.0.1-SNAPSHOT.jar > ~/EmployeeApp/app.log 2>&1 &